In [101]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [102]:
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [103]:
y = np.zeros(6)
y

array([0., 0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [104]:
sm = x + y
sm

array([1., 1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [105]:
print(f'{x.ndim},{x.dtype},{x.shape},{x.size}')

1,float64,(6,),6


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [106]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [107]:
z = np.arange(1,4, dtype = int)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [108]:
newArray = np.column_stack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [109]:
for items in newArray:
    for item in items:
        print(item)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [110]:
print(f'origin: {newArray}')
print(f'Reversed: {newArray.T}')

origin: [[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]
Reversed: [[ 1  2  3]
 [11 13 15]
 [12 14 16]]


## Q#10: Decrement all elements of "newArray" with 1.

In [111]:
newArray -= 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [112]:
np.amax(newArray)

15

In [113]:
np.amin(newArray)

0

## Q#12: Print the first row of "newArray" using indexing.

In [114]:
newArray[0]

array([ 0, 10, 11])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [115]:
newArray[1][1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [116]:
newArray[0,0]
newArray[1,2]

13

## Q#15: Change the shape of "newArray" to (9,1).

In [117]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [118]:
np.resize(newArray,(3,2))

array([[ 0, 10],
       [11,  1],
       [12, 13]])

# Well Done 🎉